name: Windows
on: 
  # push代码时触发workflow
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'
jobs:
  build:
    name: Build
    # 参考文档 https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
    runs-on: windows-latest
    strategy:
      # 矩阵配置
      matrix:
        include:
          # 6.6.0
          - qt_version: 6.6.2
            qt_arch: win64_msvc2019_64
            arch: x64
    env:
      BUILD_TYPE: Release
      BUILD_PATH: build
      assume: --release
      qt_target: 'desktop'
      qt_host: 'windows'
      # 压缩包名称
      archiveName: 'lrctotranslateQuick2-${{ matrix.qt_version }}-${{ matrix.qt_arch }}'
    # 步骤
    steps:
      # 安装Qt
      - name: Install Qt
        if: 'true'
        # 使用外部action。这个action专门用来安装Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_version }}
          host: ${{ env.qt_host }}
          target: ${{ env.qt_target }}
          arch: ${{ matrix.qt_arch }}
          install-deps: 'true'
          cache: 'true'
          aqtversion: '==3.1.*'
          modules: ${{ matrix.modules }}
          # tools: ${{ matrix.tools }}
      # 拉取代码
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true
      - name: CMake Build
        id: build
        shell: cmd
        run: |
          cmake -A ${{ matrix.arch }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=${{ env.BUILD_PATH }}/${{ env.BUILD_TYPE }} -B ${{ env.BUILD_PATH }}
          ls
      # CMake Install
      - name: CMake Install
        env:
          prefix: ${{ github.workspace }}
        shell: pwsh
        run: |
          cd ${{ github.workspace }}
          cmake --build ${{ env.BUILD_PATH }} --target install --config ${{ env.BUILD_TYPE }} -j
          ls
      # 打包 
      - name: Package
        id: package
        shell: pwsh
        env:
          path: ${{ github.workspace }}/${{ env.BUILD_PATH }}/${{ env.BUILD_TYPE }}
        run: |
          # Tree ${{ env.path }} /F

          # 拷贝依赖
          windeployqt ${{ env.assume }} --qmldir . --no-translations --compiler-runtime ${{ env.path }}/lrctotranslateQuick2.exe
          # 打包zip
          Compress-Archive -Path ${{ env.path }}/* ${{ env.archiveName }}
          # Tree ${{ env.path }} /F
          ls
      # tag 查询github-Release
      # 上传artifacts          
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.archiveName }}
          path: ${{ github.workspace }}/${{ env.BUILD_PATH }}/${{ env.BUILD_TYPE }}
      # tag 上传Release
      - name: Upload Release
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/${{ env.archiveName }}
          # asset_name: ${{ env.archiveName }}
          tag: ${{ github.ref }}
          overwrite: true 
